"""Encoder breaking raw bytes down into stable sizing for WebSocket base64 transfers."""
import base64
from typing import List

from app.config import settings


class AudioChunkEncoder:
    """
    Accumulates fragmented binary chunks from TTS generators into evenly distributed
    sizes avoiding excessive frame spam over connections or monolithic delays.
    """

    def __init__(self):
        """Initialize temporal byte store."""
        self.byte_buffer = bytearray()
        self.target_size = settings.tts_audio_chunk_size

    def encode(self, raw_audio: bytes) -> List[str]:
        """
        Process newly generated bytes pulling out stabilized chunks if caps reached.

        Args:
            raw_audio: Binary array from TTS.

        Returns:
            List[str]: Fully encoded Base64 frames ready for JSON packing.
        """
        self.byte_buffer.extend(raw_audio)
        chunks_to_emit = []

        while len(self.byte_buffer) >= self.target_size:
            chunk = self.byte_buffer[:self.target_size]
            del self.byte_buffer[:self.target_size]
            
            b64_string = base64.b64encode(chunk).decode('utf-8')
            chunks_to_emit.append(b64_string)

        return chunks_to_emit

    def flush(self) -> str:
        """
        Force serialization of trailing remaining array bits.

        Returns:
            str: Base64 final segment. Empty string if nothing remains.
        """
        if self.byte_buffer:
            b64_string = base64.b64encode(self.byte_buffer).decode('utf-8')
            self.byte_buffer.clear()
            return b64_string
        return ""
